# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: currency_converter.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'currency_converter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x63urrency_converter.proto\x12\x12\x63urrency_converter\"O\n\x11\x43onversionRequest\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x02\x12\x15\n\rfrom_currency\x18\x02 \x01(\t\x12\x13\n\x0bto_currency\x18\x03 \x01(\t\"q\n\x12\x43onversionResponse\x12\x18\n\x10\x63onverted_amount\x18\x01 \x01(\x02\x12\x15\n\rfrom_currency\x18\x02 \x01(\t\x12\x13\n\x0bto_currency\x18\x03 \x01(\t\x12\x15\n\rexchange_rate\x18\x04 \x01(\x02\x32o\n\x11\x43urrencyConverter\x12Z\n\x07\x43onvert\x12%.currency_converter.ConversionRequest\x1a&.currency_converter.ConversionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'currency_converter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONVERSIONREQUEST']._serialized_start=48
  _globals['_CONVERSIONREQUEST']._serialized_end=127
  _globals['_CONVERSIONRESPONSE']._serialized_start=129
  _globals['_CONVERSIONRESPONSE']._serialized_end=242
  _globals['_CURRENCYCONVERTER']._serialized_start=244
  _globals['_CURRENCYCONVERTER']._serialized_end=355
# @@protoc_insertion_point(module_scope)
